# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimatedGIFImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#   pod 'SDWebImage'
pod 'SDWebImage', '~> 3.7.6'
  # Pods for AnimatedGIFImage

end
